services:
  - type: web
    name: studynotion-backend
    env: node
    plan: free
    rootDir: Server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: DB_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: FOLDER_NAME
        value: "STUDYNOTION-Backend"
      - key: MAIL_HOST
        value: "smtp.gmail.com"
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: RAZORPAY_KEY
        sync: false
      - key: RAZORPAY_SECRET
        sync: false
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: CLOUD_NAME
        sync: false
